version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - "3307:3306"
    restart: unless-stopped

  pubsub-emulator:
    image: google/cloud-sdk:latest
    container_name: pubsub-emulator
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
    restart: unless-stopped
    
  consumer:
    build: ./consumer
    container_name: consumer-service
    environment:
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      PUBSUB_TOPIC_RAW: ${PUBSUB_TOPIC_RAW}
      PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql
      - pubsub-emulator
    restart: unless-stopped
